### ISSUE TITLE
Can't generate the project

### ISSUE THREAD

**Issue by andyduong1920** [nimblehq/infrastructure-templates#131]
## Issue

Getting this error when running `npx @nimblehq/infra-template@latest generate abctest`

![image](https://user-images.githubusercontent.com/11751745/202380206-b6948aef-1bf3-40bc-9332-5c11a79e0d65.png)

## Expected

The project should be generated

## Steps to reproduce

1. npx @nimblehq/infra-template@latest generate abctest

**Comment by hoangmirs** [comment]
It happened because the CLI did not get the correct template directory to copy the skeleton code.
This is the code that needs to be revised:
https://github.com/nimblehq/infrastructure-templates/blob/8d45765b6066ff218e3fadd695e6e6f0c4bdb260/src/helpers/file.ts#L29

For now, you can continue using the template by adding the `NODE_ENV=production` environment variable when running the CLI:
`NODE_ENV=production npx @nimblehq/infra-template@latest generate abctest`

**Comment by andyduong1920** [comment]
Thanks @hoangmirs the `NODE_ENV=production` works FYI 🎉

![image](https://user-images.githubusercontent.com/11751745/202388723-30d64444-1c85-44ec-aad4-a7b518abc07b.png)
